name: Build and Scan

on:
  push:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Blacklock Code Scanner
        run: |
          docker run --rm \
            -e HOST_URL=${{ secrets.SONAR_HOST_URL }} \
            -e TOKEN=${{ secrets.SONAR_TOKEN }} \
            -e PROJECT_KEY=new_maven \
            -v ${{ github.workspace }}:/github/workspace/ \
            blacklocksec/code-scanner:latest
